source 'https://github.com/CocoaPods/Specs.git'

pod 'AFNetworking', '~> 2.5.4'
pod 'ReactiveCocoa', '~> 2.5.0'

target "boilerplateTests", :exclusive => true do
    pod 'Kiwi', '~>2.3.1'
    pod 'OHHTTPStubs', '~> 4.0.2'
end
